/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com
 @idle games : http://www.gityx.com
 @QQ Group : 627141737

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置得到 + ",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Goal:": "目标:",
    "Reward": "奖励",
    "Start": "开始",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Milestone Gotten!": "获得里程碑！",
    "Milestones": "里程碑",
    "Completed": "已完成",
    "Default Save": "默认存档",
    "Delete": "删除",
    "No": "否",
    "Saves": "存档",
    "Options": "选项",
    "Yes": "是",
    "Are you sure?": "你确定吗？",
    "Edit Name": "编辑名称",
    "Info": "信息",
    "Currently:": "当前:",
    "Appearance": "外观",
    "How the game looks.": "游戏看起来如何。",
    "Theme": "主题",
    "Show milestones": "显示里程碑",
    "Show TPS meter at the bottom-left corner of the page.": "在页面左下角显示 TPS。",
    "Show TPS": "显示 TPS",
    "None": "无",
    "Align modifier units": "对齐概览单位",
    "Align numbers to the beginning of the unit in modifier view.": "在概览视图中将数字与单元的开头对齐。",
    "Select which milestones to display based on criterias.": "根据标准选择要显示的里程碑。",
    "All": "全部",
    "Classic": "经典",
    "Configurable": "可配置",
    "Duplicate": "复制",
    "Mute": "静音",
    "Unmute": "播放",
    "Join the Discord!": "加入 Discord!",
    "Fix export button and save": "修复导出按钮和保存",
    "ENABLED": "启用",
    "Export to file": "导出为文件",
    "Import clipboard": "从剪贴板导入",
    "Import file": "从文件导入",
    "DISABLED": "禁用",
    "Experience": "经验值",
    "Speed": "速度",
    "Skills": "技能",
    "Skip": "跳过",
    "Souls": "灵魂",
    "Soul Shop": "灵魂商店",
    "Soul Points": "灵魂点数",
    "Soul Points Earned:": "赚取的灵魂点数:",
    "Souls on Prestige:": "声望获得灵魂:",
    "Sound FX": "音效",
    "Sound Effects": "声音效果",
    "Fireball": "火球",
    "Skill Tree": "技能树",
    "Shop": "商店",
    "Show Combat Log": "显示战斗日志",
    "Save Data": "保存数据",
    "PRESTIGE": "声望",
    "Prestige": "声望",
    "Next": "下一个",
    "Pets": "宠物",
    "New Multiplier:": "新乘数:",
    "New Game": "新游戏",
    "Music": "音乐",
    "Music Volume": "音乐音量",
    "More": "更多",
    "Monsters Killed:": "击杀怪物:",
    "Merchant": "商人",
    "Max HP": "最大生命值",
    "Max offline time is 8 hours": "最大离线时间是8小时",
    "Mage": "法师",
    "RUNNER": "奔跑者",
    "Lv.": "等级",
    "Locked": "未解锁",
    "Made by ZombieCoco 🧟": "作者 ZombieCoco 🧟",
    "Life Crystal": "生命水晶",
    "Items": "物品",
    "Inventory": "库存",
    "Import Save": "导入存档",
    "IDLE": "放置",
    "Idle Dungeon Runner": "放置地牢奔跑者",
    "HP": "生命值",
    "Level": "等级",
    "Leave": "离开",
    "Keyboard Shortcuts": "键盘快捷键",
    "Level Reached:": "达到等级:",
    "Reset All": "重置所有",
    "Relics": "遗物",
    "Stats": "属性",
    "Stats |": "属性 |",
    "Status Effects": "状态效果",
    "💰 Sell Common": "💰 出售普通",
    "⬆️ Equip Best": "⬆️ 装备最佳",
    "Crit %": "暴击 %",
    "Display": "显示",
    "Defense": "防御",
    "Crit DMG": "暴击伤害",
    "Copy": "复制",
    "Continue": "继续",
    "Combat Log": "战斗日志",
    "Close": "关闭",
    "DUNGEON": "地牢",
    "Dungeon Depths": "地牢深度",
    "Claim Rewards": "领取奖励",
    "Earned:": "获得:",
    "Empty": "空",
    "Equip": "装备",
    "Endless Adventure Awaits": "无尽的冒险等待着你",
    "Effect description": "效果描述",
    "Daily Reward Available!": "每日奖励可用!",
    "Equipment": "装备",
    "Equipment |": "装备 |",
    "Export Save": "导出存档",
    "Evasion": "闪避",
    "Floor": "层数",
    "Floor Reached:": "达到层数:",
    "Guardian Shield": "守护之盾",
    "Hero Stats": "英雄属性",
    "High Speed & Evasion": "高速度 & 闪避",
    "High HP & Defense": "高生命值 & 防御",
    "High Damage & Crit": "高伤害 & 暴击",
    "Use Skills": "使用技能",
    "Unlocked:": "已解锁:",
    "Warrior": "战士",
    "Warrior's Blade": "战士之刃",
    "Weapon": "武器",
    "Welcome Back!": "欢迎回来!",
    "Welcome!": "欢迎!",
    "Welcome, adventurer!": "欢迎, 冒险者!",
    "XP:": "经验值:",
    "You Have Fallen!": "你失败了！",
    "You were away for": "你离开了",
    "Tutorial text here": "这是教程文本",
    "Toggle Speed": "切换速度",
    "Treasure Found!": "发现宝藏!",
    "Take All": "全部拿走",
    "Synergy": "协同",
    "Best": "最佳",
    "Audio": "音频",
    "Ascend": "转生",
    "Ascension": "转生",
    "Armor": "护甲",
    "Attack": "攻击",
    "Auto-equip better gear": "自动穿戴更好的装备",
    "Challenge": "挑战",
    "Choose Your Class": "选择你的职业",
    "Accessory": "配饰",
    "Achieve": "成就",
    "Achievement Unlocked!": "成就解锁！",
    "Activate": "激活",
    "Active Skills": "主动技能",
    "Active:": "活跃：",
    "Ancient Shrine": "上古神殿",
    "Choose Your Class": "选择你的职业",
    "Companions that follow and assist you!": "跟随和帮助你的同伴！",
    "Complete challenges for Soul Points and Relics!": "完成灵魂点数和圣物的挑战！",
    "Current Multiplier:": "当前乘数:",
    "Equip relics for powerful passive bonuses!": "装备圣物获得强大的被动加成！",
    "Hold button to buy multiple": "按住按钮购买多个",
    "Keeps: Soul Upgrades, Special Items, Achievements": "保留：灵魂升级，特殊物品，成就",
    "Milestone Unlocked!": "里程碑解锁!",
    "No active synergies. Combine class, pet, and equipment for bonuses!": "没有活跃的协同效应。职业、宠物、装备组合可获得加成！",
    "No relics found yet. Complete challenges or reach milestones!": "还没有发现任何遗物。完成挑战或达到里程碑！",
    "Prestige to gain permanent multipliers!": "声望获得永久乘数!",
    "Reach new heights of power!": "达到新的高度的力量!",
    "Resets: Floor, Level, Equipment, Run Stats": "重置：楼层，等级，装备，运行状态",
    "Rise Again": "东山再起",
    "Rogue": "流氓",
    "Shadow Cloak": "暗影披风",
    "Show Damage Numbers": "显示伤害数字",
    "Show Particles": "显示粒子",
    "Shadow Step": "影步",
    "Whirlwind": "旋风",
    "Space": "空间",
    "Statistics Dashboard": "统计面板",
    "Swift Boots": "迅捷长靴",
    "Synergies activate when conditions are met": "当条件满足时，协同作用就会启动",
    " is poisoned!": " 中毒了!",
    "You is poisoned!": "你中毒了!",
    "Warrior ⚔️": "战士 ⚔️",
    "Unlock all pets": "解锁所有宠物",
    "Total Souls": "总计灵魂",
    "Total Runs": "总运行次数",
    "Total Damage": "总伤害",
    "Regen 2% HP/sec": "恢复 2% 生命值/秒",
    "Mage 🔮": "法师 🔮",
    "MINI-BOSS": "迷你BOSS",
    "Lightning": "雷电",
    "Legendaries": "传说",
    "Legend of the Dungeon": "地牢传说",
    "Heal": "治疗",
    "Highest Hit": "最高命中",
    "Get healed 10 times": "获得 10 次治疗",
    "Spawning...": "重生中...",
    "Soul Vault": "灵魂金库",
    "Soul Banker": "灵魂银行家",
    "Soul Treasury": "灵魂宝藏",
    "Soul Saver": "灵魂拯救者",
    "Time Played": "游戏时长",
    "Morning": "早上",
    "Noon": "中午",
    "Dawn": "黎明",
    "Trap Veteran": "陷阱老兵",
    "Open!": "打开!",
    "Monsters Killed": "击杀怪物",
    "Elite Killed": "击杀精英",
    "Kill your first monster": "击杀第一只怪物",
    "Mystic Owl": "神话猫头鹰",
    "A new adventure begins...": "一场新的冒险开始了...",
    "Abyss Walker": "深渊行者",
    "All monsters defeated! An exit portal has appeared!": "所有怪物都被打败了！出现了出口传送门！",
    "Ancient Turtle": "古老的乌龟",
    "Apocalypse": "天启",
    "Arcane Shield": "奥术之盾",
    "Artifact Hoarder": "神兵囤积者",
    "Uncommon Bracelet!": "罕见的手镯！",
    "Avg Floor/Run": "平均楼层/运行",
    "Baby Phoenix": "凤凰宝宝",
    "Backstab": "背刺",
    "Battle Cry": "战斗呐喊",
    "Best Floor": "最佳楼层",
    "Better Boss loot at 25 boss kills": "在杀死25个Boss时获得更好的Boss战利品",
    "Blessed": "祝福",
    "Bosses Slain": "击杀首领",
    "Chests Opened": "宝箱开启次数",
    "Claim Reward!": "领取奖励！",
    "Come back tomorrow!": "明天再来吧！",
    "Critical Mass": "暴击批量",
    "Critical Master": "暴击大师",
    "Damage Dealer": "伤害经销商",
    "Dash": "冲刺",
    "Dashed away!": "跑掉了！",
    "Death Incarnate": "死亡化身",
    "Deep Delver": "深度挖掘",
    "Defeat a boss": "打败一个boss",
    "Defeat an elite monster": "打败一个精英怪物",
    "Devastator": "毁灭者",
    "Die for the first time": "第一次死亡",
    "DODGE": "闪避",
    "Drake Hatchling": "龙兽幼崽",
    "Dungeon Explorer": "地牢探险家",
    "Dungeon Master": "地牢大师",
    "Elite Eradicator": "精英根除者",
    "Eternal": "永恒",
    "Exterminator": "灭虫者",
    "Forged in Fire": "烈火锻造",
    "Frequent Patient": "常客",
    "Frost Assassin": "冰霜刺客",
    "Frozen enemies take +50% crit damage": "冰冻敌人受到+50%的暴击伤害",
    "Gambler": "赌徒",
    "Hoarder": "囤积狂",
    "Ice Spike": "寒冰之刺",
    "More Elite spawns at 500 kills": "500击杀时生成更多精英",
    "Never Give Up": "永不放弃",
    "No accessory equipped": "暂未装备饰品",
    "No armor equipped": "没有装备盔甲",
    "No better items to equip.": "没有更好的装备了。",
    "No common items to sell.": "暂无可出售的普通道具",
    "No weapon equipped": "没有装备武器",
    "Persistent": "持续的",
    "Pet Collector": "宠物收藏家",
    "Pet Owner": "宠物主人",
    "Poison Blade": "毒刃",
    "Prestige for the first time": "第一次获得声望",
    "Quick Descent": "速降",
    "Reborn": "重生",
    "Refreshed": "已刷新",
    "Rogue 🗡️": "流氓 🗡️",
    "ROOTED!": "扎根!",
    "Shadow Wolf": "暗影狼",
    "Shield Bash": "盾击",
    "Shopaholic": "购物狂",
    "Smoke Bomb": "烟雾弹",
    "Speed Runner": "竞速者",
    "Synergies activate when conditions are met!": "当条件满足时，协同作用就会激活！",
    "Transcendent": "超凡脱俗",
    "Treasure Seeker": "寻宝者",
    "Triggered Boulder Trap! Massive damage and knockback": "触发巨石陷阱！大量伤害和击退",
    "Triggered Poison Gas! Releases poison gas for 5 seconds": "触发毒气！释放毒气，持续5秒",
    "Triggered Spider Web! Immobilizes for 3 seconds": "触发蜘蛛网！定身3秒",
    "Undying Spirit": "不朽的灵魂",
    "Universal ⚔️": "万能⚔️",
    "Unlock 2nd Relic Slot at Floor 50": "在第50层解锁第2个遗物槽",
    "Unlock Ascension at Prestige 5": "在声望5解锁转生",
    "Unlock Challenge Modes at Floor 25": "在25层解锁挑战模式",
    "Unlock Endless Mode at Floor 100": "在100层解锁无尽模式",
    "Unlock your first pet": "解锁你的第一个宠物",
    "Veteran Bonus after 1 hour played": "1个小时后的老兵奖励",
    "Thunderstorm": "雷雨",
    " Rage": "狂怒",
    "Attack Potion (+25% ATK, 60s) - 20 SP": "攻击药水（+25%攻击力，持续60秒）- 20 灵魂点数",
    "Defense Potion (+25% DEF, 60s) - 20 SP": "防御药剂（+25%防御，持续60秒）- 20 灵魂点数",
    "Elites Killed": "击杀精英",
    "Find a legendary item": "发现一个传说物品",
    "Health Potion (Heal 30%) - 10 SP": "生命药水（治疗30%）- 10 灵魂点数",
    "Speed Potion (+30% SPD, 60s) - 15 SP": "加速药水（+30% 速度， 持续60秒）- 15 灵魂点数",
    "Traveling Merchant": "旅行商人",
    "Want to buy something?": "想买点东西吗？",
    "+FULL": "+满",
    " is burned!": " 被点燃了!",
    "You is burned!": "你被点燃了!",
    "You is freezeed!": "你被冰冻了!",
    " is freezeed!": " 被冰冻了!",
    "Weapon upgraded!": "武器 已升级!",
    "Upgraded speed!": "升级了 速度!",
    "Upgraded maxHp!": "升级了 最大生命值!",
    "Upgraded evasion!": "升级了 闪避!",
    "Upgraded defense!": "升级了 防御!",
    "Upgraded attack!": "升级了 攻击!",
    "Upgraded critChance!": "升级了 暴击率!",
    "'s shield broke!": "的盾牌坏掉了!",
    " raises a shield!": " 举起了盾牌！",
    " becomes enraged!": " 被激怒了!",
    "Afternoon": "下午",
    "ALARM!": "警报！",
    "ASCEND": "上升",
    "attack buff expired!": "攻击buff过期了！",
    "BOSS": "boss",
    "Boss Rush": "Boss冲刺",
    "Bought Attack Potion (+25% ATK, 60s)!": "购买攻击药水（+25%攻击力，60秒）！",
    "Current Tier: None": "当前层级：无",
    "Dense Fog": "浓雾",
    "Dungeon Blacksmith": "地牢铁匠",
    "Dusk": "黄昏",
    "Evening": "晚上",
    "Fight 10 bosses in a row": "连续打败10个boss",
    "Fountain fully restored your health!": "喷泉恢复了你全部的生命值！",
    "Glass Cannon": "玻璃大炮",
    "Good! x5": "很好！x5",
    "Healed to full health!": "治愈到满血！",
    "Healing Fountain": "疗愈的喷泉",
    "I can upgrade your gear!": "我可以升级你的装备！",
    "Iron Will": "钢铁般的意志",
    "Let me heal your wounds.": "让我来治愈你的伤口。",
    "Midnight": "午夜",
    "Wolf pet 50% off at Floor 10": "狼宠物在10层打5折",
    "Naked Run": "裸奔",
    " raises the dead!": " 让死人复活！",
    "Next: Novice (1.0K SP)": "下一个：新手（1.0K 灵魂点数）",
    "Night": "晚上",
    "Pacifist": "和平主义者",
    "Reach floor 10 without attacking": "在不攻击的情况下到达10层",
    "Reach floor 15 without healing": "在没有治疗的情况下到达15层",
    "Reach floor 20 in 5 minutes": "在5分钟内到达20层",
    "Reach floor 25 without equipment": "无装备达到25层",
    "Restore to full HP": "回复满血",
    "Skipped Healing Fountain": "跳过治疗之泉",
    "Speed Run": "快速运行",
    "Triggered Alarm Trap! Spawns additional monsters": "触发警报陷阱！生成额外的怪物",
    "Triggered Ice Trap! Slows movement by 50% for 3s": "触发寒冰陷阱！使移动速度降低50%，持续3秒",
    "Triggered Teleporter! Teleports to random location": "触发传送！传送到任意位置",
    "Volcanic Ash": "火山灰",
    "Wandering Healer": "流浪治疗师",
    "tle Cry": "无声的哭泣",
    "Auto-Combat": "自动战斗",
    "Snowfall": "降雪",
    "Welcome to Idle Dungeon Runner! Your hero automatically fights monsters and explores dungeons.": "欢迎来到《放置地牢跑酷》！你的英雄会自动与怪物战斗并探索地牢。",
    "Your hero moves and attacks automatically. Watch them clear the floor!": "你的英雄会自动移动和攻击。看着他们清理楼层！",
    "Triggered Spike Trap! Sharp spikes deal 15% HP damage": "触发尖刺陷阱！尖刺造成15%生命值伤害",
    "+20% Attack for 60s": "+20%攻击，持续60秒",
    "+20% Defense for 60s": "+20%防御，持续60秒",
    "Skipped Ancient Shrine": "跳过古代神殿",
    "Active": "活跃",
    "Select": "选择",
    "Shadow Wolf is now your companion!": "暗影狼现在是你的伙伴了！",
    "Unlocked Shadow Wolf!": "解锁暗影狼！",
    "Speed Run!": "极速奔跑！",
    "Fountain increased your Max HP by 20!": "喷泉为你增加了20点生命上限！",
    "Rain": "下雨",
    "+10% legendary drop rate with 3+ legendaries": "+10%的传奇掉落率与3+传奇掉落率",
    "🦉 Pet evolved into Mystic Owl!": "🦉 宠物进化成神话猫头鹰！",
    "+20% Attack for 60s": "攻击+20%，持续60秒",
    "Arcane Storm": "奥术风暴",
    "Bought Speed Potion (+30% SPD, 60s)!": "购买速度药水（+30% SPD， 60秒）！",
    "Mystic Owl!": "神话猫头鹰！",
    "Mystic Owl is now your companion!": "神话猫头鹰现在是你的同伴！",
    "Pet dismissed.": "宠物解散了。",
    "Shadow Step!": "影步！",
    "Unlocked Mystic Owl!": "解锁神话猫头鹰！",
    "Restore 50% HP": "恢复50%生命值",
    "Sandstorm": "沙尘暴",
    "SECRET: Dimensional Rift!": "秘密：维度裂缝！",
    "Triggered Fire Trap! Burns for 20% HP and applies burn": "触发了火焰陷阱！燃烧20%生命值，并附加灼烧效果",
    "SECRET: Secret Armory!": "秘密：秘密军械库！",
    "Veteran Bonus after 1 hour played": "玩1个小时后的老兵奖励",
    "SECRET: Ancient Shrine!": "秘密：古代神殿！",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    " Shield": "盾牌",
    " dropped Legendary Staff!": "掉落了 传说的法杖!",
    " dropped Legendary Amulet!": "掉落了 传说的护身符!",
    " dropped Legendary Scale!": "掉落了 传说的鳞片!",
    " dropped Legendary Cloak!": "掉落了 传说的披风!",
    " dropped Legendary Chainmail!": "掉落了 传说的链甲!",
    " dropped Legendary Dagger!": "掉落了 传说的匕首!",
    " dropped Legendary Bow!": "掉落了 传说的弓!",
    " dropped Legendary Plate!": "掉落了 传说的板甲!",
    " dropped Legendary Sword!": "掉落了 传说的剑!",
    " dropped Legendary Hammer!": "掉落了 传说的锤子!",
    " dropped Legendary Spear!": "掉落了 传说的长矛!",
    " dropped Legendary Bracelet!": "掉落了 传说的手镯!",
    " dropped Legendary Ring!": "掉落了 传说的戒指!",
    " dropped Legendary Crown!": "掉落了 传说的王冠!",
    " dropped Legendary Axe!": "掉落了 传说的斧子!",
    " dropped Legendary Belt!": "掉落了 传说的腰带!",
    " dropped Legendary Robes!": "掉落了 传说的长袍!",
    " dropped Legendary Leather!": "掉落了 传说的皮革!",
    " dropped Rare Staff!": "掉落了 稀有的法杖!",
    " dropped Rare Scale!": "掉落了 稀有的鳞片!",
    " dropped Rare Cloak!": "掉落了 稀有的披风!",
    " dropped Rare Chainmail!": "掉落了 稀有的链甲!",
    " dropped Rare Dagger!": "掉落了 稀有的匕首!",
    " dropped Rare Bow!": "掉落了 稀有的弓!",
    " dropped Rare Sword!": "掉落了 稀有的剑!",
    " dropped Rare Amulet!": "掉落了 稀有的护身符!",
    " dropped Rare Hammer!": "掉落了 稀有的锤子!",
    " dropped Rare Plate!": "掉落了 稀有的板甲!",
    " dropped Rare Spear!": "掉落了 稀有的长矛!",
    " dropped Rare Bracelet!": "掉落了 稀有的手镯!",
    " dropped Rare Ring!": "掉落了 稀有的戒指!",
    " dropped Rare Crown!": "掉落了 稀有的王冠!",
    " dropped Rare Axe!": "掉落了 稀有的斧子!",
    " dropped Rare Belt!": "掉落了 稀有的腰带!",
    " dropped Rare Robes!": "掉落了 稀有的长袍!",
    " dropped Rare Leather!": "掉落了 稀有的皮革!",
    " dropped Epic Scale!": "掉落了 史诗的鳞片!",
    " dropped Epic Chainmail!": "掉落了 史诗的链甲!",
    " dropped Epic Dagger!": "掉落了 史诗的匕首!",
    " dropped Epic Bow!": "掉落了 史诗的弓!",
    " dropped Epic Staff!": "掉落了 史诗的法杖!",
    " dropped Epic Plate!": "掉落了 史诗的板甲!",
    " dropped Epic Sword!": "掉落了 史诗的剑!",
    " dropped Epic Hammer!": "掉落了 史诗的锤子!",
    " dropped Epic Spear!": "掉落了 史诗的长矛!",
    " dropped Epic Bracelet!": "掉落了 史诗的手镯!",
    " dropped Epic Amulet!": "掉落了 史诗的护身符!",
    " dropped Epic Ring!": "掉落了 史诗的戒指!",
    " dropped Epic Cloak!": "掉落了 史诗的披风!",
    " dropped Epic Crown!": "掉落了 史诗的王冠!",
    " dropped Epic Axe!": "掉落了 史诗的斧子!",
    " dropped Epic Belt!": "掉落了 史诗的腰带!",
    " dropped Epic Robes!": "掉落了 史诗的长袍!",
    " dropped Epic Leather!": "掉落了 史诗的皮革!",
    " dropped Uncommon Scale!": "掉落了 罕见的鳞片!",
    " dropped Uncommon Staff!": "掉落了 罕见的法杖!",
    " dropped Uncommon Plate!": "掉落了 罕见的板甲!",
    " dropped Uncommon Chainmail!": "掉落了 罕见的链甲!",
    " dropped Uncommon Dagger!": "掉落了 罕见的匕首!",
    " dropped Uncommon Bow!": "掉落了 罕见的弓!",
    " dropped Uncommon Amulet!": "掉落了 罕见的护身符!",
    " dropped Uncommon Sword!": "掉落了 罕见的剑!",
    " dropped Uncommon Cloak!": "掉落了 罕见的披风!",
    " dropped Uncommon Hammer!": "掉落了 罕见的锤子!",
    " dropped Uncommon Spear!": "掉落了 罕见的长矛!",
    " dropped Uncommon Bracelet!": "掉落了 罕见的手镯!",
    " dropped Uncommon Ring!": "掉落了 罕见的戒指!",
    " dropped Uncommon Crown!": "掉落了 罕见的王冠!",
    " dropped Uncommon Axe!": "掉落了 罕见的斧子!",
    " dropped Uncommon Belt!": "掉落了 罕见的腰带!",
    " dropped Uncommon Robes!": "掉落了 罕见的长袍!",
    " dropped Uncommon Leather!": "掉落了 罕见的皮革!",
    " dropped Common Plate!": "掉落了 普通的板甲!",
    " dropped Common Scale!": "掉落了 普通的鳞片!",
    " dropped Common Chainmail!": "掉落了 普通的链甲!",
    " dropped Common Amulet!": "掉落了 普通的护身符!",
    " dropped Common Dagger!": "掉落了 普通的匕首!",
    " dropped Common Staff!": "掉落了 普通的法杖!",
    " dropped Common Bow!": "掉落了 普通的弓!",
    " dropped Common Cloak!": "掉落了 普通的披风!",
    " dropped Common Sword!": "掉落了 普通的剑!",
    " dropped Common Hammer!": "掉落了 普通的锤子!",
    " dropped Common Spear!": "掉落了 普通的长矛!",
    " dropped Common Bracelet!": "掉落了 普通的手镯!",
    " dropped Common Ring!": "掉落了 普通的戒指!",
    " dropped Common Crown!": "掉落了 普通的王冠!",
    " dropped Common Axe!": "掉落了 普通的斧子!",
    " dropped Common Belt!": "掉落了 普通的腰带!",
    " dropped Common Robes!": "掉落了 普通的长袍!",
    " dropped Common Leather!": "掉落了 普通的皮革!",
    "SP": "灵魂点数",
    // 图标代码，不能汉化
    "Jacorb's Games": "Jacorb's Games",
    "/": "/",
    "×": "×",
    "▶️": "▶️",
    "★": "★",
    "⚔️": "⚔️",
    "⚙️": "⚙️",
    "🌀": "🌀",
    "🎮": "🎮",
    "💀": "💀",
    "💎": "💎",
    "💚": "💚",
    "💨": "💨",
    "📊": "📊",
    "📦": "📦",
    "🔥": "🔥",
    "🚪": "🚪",
    "🛒": "🛒",
    "🛡️": "🛡️",
    "?": "?",
    "⌚": "⌚",
    "⚡": "⚡",
    "👘": "👘",
    "👤": "👤",
    "💍": "💍",
    "📢": "📢",
    "🔨": "🔨",
    "🔮": "🔮",
    "🗡️": "🗡️",
    "🧊": "🧊",
    "🧪": "🧪",
    "😤": "😤",
    "!": "!",
    "⛓️": "⛓️",
    "🎗️": "🎗️",
    "🏹": "🏹",
    "🐉": "🐉",
    "👑": "👑",
    "📿": "📿",
    "🔱": "🔱",
    "🥋": "🥋",
    "🧥": "🧥",
    "🪄": "🪄",
    "🪓": "🪓",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "+": "+",
    ".": ".",
    "…": "…",
    ":": ":",
    "-": "-",
    "|": "|",
    "(": "(",
    ")": ")",
    "Scientific": "科学计数法",
    "Standard": "标准",
    "Blind": "盲文",
    "Letters": "字母",
    "Mixed Engineering": "混合工程",
    "Mixed Scientific": "混合科学",
    "Chemistry": "化学",
    "Engineering": "工程符号",
    "By Jacorb90": "By Jacorb90",
    "content_copy": "content_copy",
    "library_books": "library_books",
    "discord": "discord",
    "drag_handle": "drag_handle",
    "edit": "edit",
    "forum": "forum",
    "content_paste": "content_paste",
    "delete": "delete",
    "info": "info",
    "settings": "settings",
    'Twitter': 'Twitter',
    "Discord": "Discord",
    "Facebook": "Facebook",
    "Instagram": "Instagram",
    "gityxcom": "gityxcom",
    "Footer": "Footer",
    "Wiki": "Wiki",
    "gityx": "gityx",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    'Gityx游戏': 'Gityx游戏',
    'Git游戏': 'Git游戏',
    'QQ群号': 'QQ群号',
    'x': 'x',
    'QQ群号:': 'QQ群号:',
    '* 启用后台游戏': '* 启用后台游戏',
    '更多同类游戏:': '更多同类游戏:',
    'i': 'i',
    'I': 'I',
    'II': 'II',
    'III': 'III',
    'IV': 'IV',
    'V': 'V',
    'VI': 'VI',
    'VII': 'VII',
    'VIII': 'VIII',
    'X': 'X',
    'XI': 'XI',
    'XII': 'XII',
    'XIII': 'XIII',
    'XIV': 'XIV',
    'XV': 'XV',
    'XVI': 'XVI',
    'A': 'A',
    'B': 'B',
    'C': 'C',
    'D': 'D',
    'E': 'E',
    'F': 'F',
    'G': 'G',
    'H': 'H',
    'I': 'I',
    'J': 'J',
    'K': 'K',
    'L': 'L',
    'M': 'M',
    'N': 'N',
    'O': 'O',
    'P': 'P',
    'Q': 'Q',
    'R': 'R',
    'S': 'S',
    'T': 'T',
    'U': 'U',
    'V': 'V',
    'W': 'W',
    'X': 'X',
    'Y': 'Y',
    'Z': 'Z',
    'a': 'a',
    'b': 'b',
    'c': 'c',
    'd': 'd',
    'e': 'e',
    'f': 'f',
    'g': 'g',
    'h': 'h',
    'i': 'i',
    'j': 'j',
    'k': 'k',
    'l': 'l',
    'm': 'm',
    'n': 'n',
    'o': 'o',
    'p': 'p',
    'q': 'q',
    'r': 'r',
    's': 's',
    't': 't',
    'u': 'u',
    'v': 'v',
    'w': 'w',
    'x': 'x',
    'y': 'y',
    'z': 'z',
    '<': '<',
    '<<': '<<',
    '>': '>',
    '>>': '>>',
    'Jan': '1月',
    'Feb': '2月',
    'Mar': '3月',
    'Apr': '4月',
    'May': '5月',
    'Jun': '6月',
    'Jul': '7月',
    'Aug': '8月',
    'Sep': '9月',
    'Oct': '10月',
    'Nov': '11月',
    'Dec': '12月',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',

}


//需处理的前缀，此处可以截取语句开头部分的内容进行汉化
//例如：Coin: 13、Coin: 14、Coin: 15... 这种有相同开头的语句
//可以在这里汉化开头："Coin: ":"金币: "
var cnPrefix = {
    "\n": "\n",
    "                   ": "                   ",
    "                  ": "                  ",
    "                 ": "                 ",
    "                ": "                ",
    "               ": "               ",
    "              ": "              ",
    "             ": "             ",
    "            ": "            ",
    "           ": "           ",
    "          ": "          ",
    "         ": "         ",
    "        ": "        ",
    "       ": "       ",
    "      ": "      ",
    "     ": "     ",
    "    ": "    ",
    "   ": "   ",
    "  ": "  ",
    " ": " ",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Shift-Click to Toggle Tooltips: ": "Shift-单击以切换工具提示：",
    "Notation: ": "符号: ",
    "Toggle Music: ": "切换声音: ",
    "Animations: ": "动画: ",
    "Current Endgame: ": "当前终局: ",
    "Space Background: ": "太空背景: ",
    "Skill: ": "技能: ",
    "Version ": "版本 ",
    "Zombie": "僵尸",
    "Rat": "老鼠",
    "Orc": "兽人",
    "Golem": "魔像",
    "Goblin": "哥布林",
    "Achievement: ": "成就: ",
    "Berserker": "狂战士",
    "CRIT! ": "暴击! ",
    "Time: ": "时间: ",
    "Necromancer": "死灵法师",
    "Troll": "巨魔",
    "Skeleton": "骷髅",
    "Wolf": "狼",
    "Snake": "蛇",
    "Spider": "蜘蛛",
    "Auto-equipped ": "自动装备 ",
    "Opened chest! Found ": "打开宝箱! 发现 ",
    "First Death": "第一条命",
    "First Blood": "第一滴血",
    "Getting Started": "入门",
    "Boss Destroyer": "Boss破坏者",
    "Legendary Collector": "传说收集者",
    "Monster Slayer": "怪物杀手",
    "Treasure Hunter": "宝藏猎人",
    "Treasure Master": "宝藏大师",
    "Boss Hunter": "Boss猎人",
    "Trap Survivor": "陷阱幸存者",
    "Boss Slayer": "Boss杀手",
    "Weather changed to: ": "天气转变为：",
    "Vampire": "吸血鬼",
    "Slime": "史莱姆",
    "Slime King": "史莱姆之王",
    "Bat": "蝙蝠",
    "Dark Elf": "暗精灵",
    "Demon": "恶魔",
    "Assassin": "刺客",
    "Guardian": "守护者",
    "Wraith": "幽灵",
    "Elite Zombie": "精英僵尸",
    "Elite Troll": "精英巨魔",
    "Elite Spider": "精英蜘蛛",
    "Elite Slime": "精英史莱姆",
    "Elite Bat": "精英蝙蝠",
    "Elite Dark Elf": "精英暗精灵",
    "Elite Hunter": "精英猎人",
    "Elite Goblin": "精英哥布林",
    "Elite Wolf": "精英狼",
    "Elite Vampire": "精英吸血鬼",
    "Elite Snake": "精英蛇",
    "Elite ark Elf": "精英暗精灵",
    "Elite Demon": "精英恶魔",
    "Elite Wraith": "精英幽灵",
    "Elite Golem": "精英魔像",
    "Elite Rat": "精英老鼠",
    "Elite Slayer": "精英杀手",
    "Elite Skeleton": "精英骷髅",
    "Elite Orc": "精英兽人",
    "Unlocks: ": "解锁: ",
    "Common Plate": "普通的板甲",
    "Common Robes": "普通的长袍",
    "Common Hammer": "普通的锤子",
    "Common Bow": "普通的弓",
    "Common Staff": "普通的法杖",
    "Common Belt": "普通的腰带",
    "Common Amulet": "普通的护身符",
    "Common Axe": "普通的斧子",
    "Common Spear": "普通的长矛",
    "Common Scale": "普通的鳞片",
    "Common Ring": "普通的戒指",
    "Common Bracelet": "普通的手镯",
    "Common Crown": "普通的王冠",
    "Common Cloak": "普通的披风",
    "Common Chainmail": "普通的链甲",
    "Common Leather": "普通的皮革",
    "Common Dagger": "普通的匕首",
    "Common Sword": "普通的剑",
    "Uncommon Plate": "罕见的板甲",
    "Uncommon Robes": "罕见的长袍",
    "Uncommon Hammer": "罕见的锤子",
    "Uncommon Bow": "罕见的弓",
    "Uncommon Staff": "罕见的法杖",
    "Uncommon Belt": "罕见的腰带",
    "Uncommon Amulet": "罕见的护身符",
    "Uncommon Axe": "罕见的斧子",
    "Uncommon Spear": "罕见的长矛",
    "Uncommon Scale": "罕见的鳞片",
    "Uncommon Ring": "罕见的戒指",
    "Uncommon Bracelet": "罕见的手镯",
    "Uncommon Crown": "罕见的王冠",
    "Uncommon Cloak": "罕见的披风",
    "Uncommon Chainmail": "罕见的链甲",
    "Uncommon Leather": "罕见的皮革",
    "Uncommon Dagger": "罕见的匕首",
    "Uncommon Sword": "罕见的剑",
    "Rare Robes": "稀有的长袍",
    "Rare Plate": "稀有的板甲",
    "Rare Hammer": "稀有的锤子",
    "Rare Bow": "稀有的弓",
    "Rare Staff": "稀有的法杖",
    "Rare Belt": "稀有的腰带",
    "Rare Amulet": "稀有的护身符",
    "Rare Axe": "稀有的斧子",
    "Rare Spear": "稀有的长矛",
    "Rare Scale": "稀有的鳞片",
    "Rare Ring": "稀有的戒指",
    "Rare Bracelet": "稀有的手镯",
    "Rare Crown": "稀有的王冠",
    "Rare Cloak": "稀有的披风",
    "Rare Chainmail": "稀有的链甲",
    "Rare Leather": "稀有的皮革",
    "Rare Dagger": "稀有的匕首",
    "Rare Sword": "稀有的剑",
    "Epic Robes": "史诗的长袍",
    "Epic Hammer": "史诗的锤子",
    "Epic Bow": "史诗的弓",
    "Epic Staff": "史诗的法杖",
    "Epic Belt": "史诗的腰带",
    "Epic Plate": "史诗的板甲",
    "Epic Amulet": "史诗的护身符",
    "Epic Axe": "史诗的斧子",
    "Epic Spear": "史诗的长矛",
    "Epic Scale": "史诗的鳞片",
    "Epic Ring": "史诗的戒指",
    "Epic Bracelet": "史诗的手镯",
    "Epic Crown": "史诗的王冠",
    "Epic Cloak": "史诗的披风",
    "Epic Chainmail": "史诗的链甲",
    "Epic Leather": "史诗的皮革",
    "Epic Dagger": "史诗的匕首",
    "Epic Sword": "史诗的剑",
    "Legendary Plate": "传说的板甲",
    "Legendary Robes": "传说的长袍",
    "Legendary Hammer": "传说的锤子",
    "Legendary Bow": "传说的弓",
    "Legendary Staff": "传说的法杖",
    "Legendary Belt": "传说的腰带",
    "Legendary Amulet": "传说的护身符",
    "Legendary Axe": "传说的斧子",
    "Legendary Spear": "传说的长矛",
    "Legendary Scale": "传说的鳞片",
    "Legendary Ring": "传说的戒指",
    "Legendary Bracelet": "传说的手镯",
    "Legendary Crown": "传说的王冠",
    "Legendary Cloak": "传说的披风",
    "Legendary Chainmail": "传说的链甲",
    "Legendary Leather": "传说的皮革",
    "Legendary Dagger": "传说的匕首",
    "Legendary Sword": "传说的剑",
    "Legendary Find": "传说发现",
    "Ascended": "转生",
    "Slots: ": "槽位: ",
    "Heal to full ": "治疗至满血 ",
    "PRESTIGE! New multiplier: ": "声望! 新乘数: ",
    "Challenge started: ": "挑战开始了：",
    "Persistent": "持续的",
    "Upgrade Weapon (+10% ATK) - ": "武器升级（+10%攻击）- ",
    "Ancient Shrine: ": "上古神殿: ",
    "EVOLVED: ": "已进化: ",
    "Milestone Unlocked: ": "里程碑解锁：",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀，此处可以截取语句结尾部分的内容进行汉化
//例如：13 Coin、14 Coin、15 Coin... 这种有相同结尾的语句
//可以在这里汉化结尾：" Coin":" 金币"
var cnPostfix = {
    "                   ": "                   ",
    "                  ": "                  ",
    "                 ": "                 ",
    "                ": "                ",
    "               ": "               ",
    "              ": "              ",
    "             ": "             ",
    "            ": "            ",
    "           ": "           ",
    "          ": "          ",
    "         ": "         ",
    "        ": "        ",
    "       ": "       ",
    "      ": "      ",
    "     ": "     ",
    "    ": "    ",
    "   ": "   ",
    "  ": "  ",
    " ": " ",
    "\n": "\n",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "/sec)": "/秒)",
    ' I': ' I',
    ' II': ' II',
    ' III': ' III',
    ' IV': ' IV',
    ' V': ' V',
    ' VI': ' VI',
    ' VII': ' VII',
    ' VIII': ' VIII',
    ' X': ' X',
    ' XI': ' XI',
    ' XII': ' XII',
    ' XIII': ' XIII',
    ' XIV': ' XIV',
    ' XV': ' XV',
    ' XVI': ' XVI',
    "[Tap to unequip]": "[点击脱下]",
    "[Tap to equip]": "[点击穿上]",
    " uses AoE attack!": " 使用了 AoE 攻击!",
    "Elite Zombie": "精英僵尸",
    "Elite Troll": "精英巨魔",
    "Elite Spider": "精英蜘蛛",
    "Elite Slime": "精英史莱姆",
    "Elite Bat": "精英蝙蝠",
    "Elite Dark Elf": "精英暗精灵",
    "Elite Hunter": "精英猎人",
    "Elite Goblin": "精英哥布林",
    "Elite Wolf": "精英狼",
    "Elite Vampire": "精英吸血鬼",
    "Elite Snake": "精英蛇",
    "Elite ark Elf": "精英暗精灵",
    "Elite Demon": "精英恶魔",
    "Elite Wraith": "精英幽灵",
    "Elite Golem": "精英魔像",
    "Elite Rat": "精英老鼠",
    "Elite Slayer": "精英杀手",
    "Elite Skeleton": "精英骷髅",
    "Elite Orc": "精英兽人",
    "Unlocks: ": "解锁: ",
    "Common Plate": "普通的板甲",
    "Common Robes": "普通的长袍",
    "Common Hammer": "普通的锤子",
    "Common Bow": "普通的弓",
    "Common Staff": "普通的法杖",
    "Common Belt": "普通的腰带",
    "Common Amulet": "普通的护身符",
    "Common Axe": "普通的斧子",
    "Common Spear": "普通的长矛",
    "Common Scale": "普通的鳞片",
    "Common Ring": "普通的戒指",
    "Common Bracelet": "普通的手镯",
    "Common Crown": "普通的王冠",
    "Common Cloak": "普通的披风",
    "Common Chainmail": "普通的链甲",
    "Common Leather": "普通的皮革",
    "Common Dagger": "普通的匕首",
    "Common Sword": "普通的剑",
    "Uncommon Plate": "罕见的板甲",
    "Uncommon Robes": "罕见的长袍",
    "Uncommon Hammer": "罕见的锤子",
    "Uncommon Bow": "罕见的弓",
    "Uncommon Staff": "罕见的法杖",
    "Uncommon Belt": "罕见的腰带",
    "Uncommon Amulet": "罕见的护身符",
    "Uncommon Axe": "罕见的斧子",
    "Uncommon Spear": "罕见的长矛",
    "Uncommon Scale": "罕见的鳞片",
    "Uncommon Ring": "罕见的戒指",
    "Uncommon Bracelet": "罕见的手镯",
    "Uncommon Crown": "罕见的王冠",
    "Uncommon Cloak": "罕见的披风",
    "Uncommon Chainmail": "罕见的链甲",
    "Uncommon Leather": "罕见的皮革",
    "Uncommon Dagger": "罕见的匕首",
    "Uncommon Sword": "罕见的剑",
    "Rare Robes": "稀有的长袍",
    "Rare Plate": "稀有的板甲",
    "Rare Hammer": "稀有的锤子",
    "Rare Bow": "稀有的弓",
    "Rare Staff": "稀有的法杖",
    "Rare Belt": "稀有的腰带",
    "Rare Amulet": "稀有的护身符",
    "Rare Axe": "稀有的斧子",
    "Rare Spear": "稀有的长矛",
    "Rare Scale": "稀有的鳞片",
    "Rare Ring": "稀有的戒指",
    "Rare Bracelet": "稀有的手镯",
    "Rare Crown": "稀有的王冠",
    "Rare Cloak": "稀有的披风",
    "Rare Chainmail": "稀有的链甲",
    "Rare Leather": "稀有的皮革",
    "Rare Dagger": "稀有的匕首",
    "Rare Sword": "稀有的剑",
    "Epic Robes": "史诗的长袍",
    "Epic Hammer": "史诗的锤子",
    "Epic Bow": "史诗的弓",
    "Epic Staff": "史诗的法杖",
    "Epic Belt": "史诗的腰带",
    "Epic Plate": "史诗的板甲",
    "Epic Amulet": "史诗的护身符",
    "Epic Axe": "史诗的斧子",
    "Epic Spear": "史诗的长矛",
    "Epic Scale": "史诗的鳞片",
    "Epic Ring": "史诗的戒指",
    "Epic Bracelet": "史诗的手镯",
    "Epic Crown": "史诗的王冠",
    "Epic Cloak": "史诗的披风",
    "Epic Chainmail": "史诗的链甲",
    "Epic Leather": "史诗的皮革",
    "Epic Dagger": "史诗的匕首",
    "Epic Sword": "史诗的剑",
    "Legendary Plate": "传说的板甲",
    "Legendary Robes": "传说的长袍",
    "Legendary Hammer": "传说的锤子",
    "Legendary Bow": "传说的弓",
    "Legendary Staff": "传说的法杖",
    "Legendary Belt": "传说的腰带",
    "Legendary Amulet": "传说的护身符",
    "Legendary Axe": "传说的斧子",
    "Legendary Spear": "传说的长矛",
    "Legendary Scale": "传说的鳞片",
    "Legendary Ring": "传说的戒指",
    "Legendary Bracelet": "传说的手镯",
    "Legendary Crown": "传说的王冠",
    "Legendary Cloak": "传说的披风",
    "Legendary Chainmail": "传说的链甲",
    "Legendary Leather": "传说的皮革",
    "Legendary Dagger": "传说的匕首",
    "Legendary Sword": "传说的剑",
    "Legendary Find": "传说发现",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)h$/,
    /^([\d\.]+)m$/,
    /^([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)y ([\d\.]+)d ([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)y ([\d\.]+)d ([\d\.]+)h$/,
    /^([\d\.]+)\-([\d\.]+)\-([\d\.]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)$/,
    /^×([\d\.]+)$/,
    /^x([\d\.]+)$/,
    /^v([\d\.]+)$/,
    /^\$([\d\.]+)$/,
    /^\(([\d\.]+)\)$/,
    /^([\d\.]+)\%$/,
    /^\+([\d\.]+)\%$/,
    /^\-([\d\.]+)\%$/,
    /^([\d\.]+)\/([\d\.]+)$/,
    /^\-([\d\.]+)\/([\d\.]+)$/,
    /^([\d\.]+)\/([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.,]+)$/,
    /^([\d\.,]+)\-([\d\.,]+)$/,
    /^\(([\d\.]+)\/([\d\.]+)\)$/,
    /^\(([\d\.]+),([\d\.]+)\)$/,
    /^\(\-([\d\.]+),([\d\.]+)\)$/,
    /^\(\-([\d\.]+),\-([\d\.]+)\)$/,
    /^\(([\d\.]+),\-([\d\.]+)\)$/,
    /^成本(.+)$/,
    /^\(([\d\.]+)\%\)$/,
    /^\[([\d\.]+)\]$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)\-([\d\.]+)\-([\d\.]+) ([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^\[([\d\.]+):([\d\.]+):([\d\.]+)\]$/,
    /^([\d\.]+)K$/,
    /^([\d\.]+)M$/,
    /^([\d\.]+)B$/,
    /^([\d\.]+) K$/,
    /^([\d\.]+) M$/,
    /^([\d\.]+) B$/,
    /^([\d\.]+) T$/,
    /^([\d\.]+) Qi$/,
    /^([\d\.]+) Qa$/,
    /^([\d\.]+) Sp$/,
    /^([\d\.]+) Oc$/,
    /^([\d\.]+) Dc$/,
    /^([\d\.]+) UDc$/,
    /^([\d\.]+) No$/,
    /^([\d\.]+) Sx$/,
    /^([\d\.]+) QaDc$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^x([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^\$([\d\.,]+)$/,
    /^\+([\d\.,]+)$/,
    /^\-([\d\.,]+)$/,
    /^([\d\.,]+)x$/,
    /^x([\d\.,]+)$/,
    /^×([\d\.,]+)$/,
    /^([\d\.,]+) \/ ([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+) \/ ([\d\.]+)e([\d\.,]+)$/,
    /^\$([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e\+([\d\.,]+)$/,
    /^e([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    // /^([\uD800-\uDBFF][\uDC00-\uDFFF])|([\u2600-\u27BF])|([\u2300-\u23FF])|([\u2B50-\u2B55])|([\u203C-\u3299])|[\u21A9\u21AA\u25B6\u25C0\u2B06\u2B07\u2B05\u2B95\u2B99\u2B9A]+$/,
    // /^([\uD800-\uDBFF][\uDC00-\uDFFF])|([\u2600-\u27BF])|([\u2300-\u23FF])|([\u2B50-\u2B55])|([\u203C-\u3299])+$/,
    // /^[\uD800-\uFFFF]+$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//字母加数字：([\d\.]+[A-Za-z])
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
//&nbsp;空格：\xA0
var cnRegReplace = new Map([
    [/^([\d\.]+) hours ([\d\.]+) minutes ([\d\.]+) seconds$/, '$1 小时 $2 分钟 $3 秒'],
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
    [/^Daily Reward Day (.+): (.+) Soul Points$/, '每日奖励第 $1 天：$2 灵魂点数'],
    [/^Healed for (.+) HP!$/, '治疗了 $1 生命值!'],
    [/^Whirlwind hits (.+) enemies!$/, '旋风攻击了 $1 敌人!'],
    [/^ \(common\)\nATK (.+), SPD (.+)\n$/, ' (普通)\n攻击 $1, 速度 $2\n'],
    [/^ \(common\)\nATK (.+)\n$/, ' (普通)\n攻击 $1\n'],
    [/^ \(common\)\nDEF (.+), HP (.+)\n$/, ' (普通)\n防御 $1, 生命值 $2\n'],
    [/^ \(common\)\nDEF (.+), SPD (.+)\n$/, ' (普通)\n防御 $1, 速度 $2\n'],
    [/^ \(common\)\nHP (.+)\n$/, ' (普通)\n生命值 $1\n'],
    [/^ \(uncommon\)\nATK (.+), CRIT (.+)\n$/, ' (罕见)\n攻击 $1, 暴击率 $2\n'],
    [/^ \(uncommon\)\nDEF (.+), HP (.+)\n$/, ' (罕见)\n防御 $1, 生命值 $2\n'],
    [/^ \(uncommon\)\nDEF (.+), SPD (.+)\n$/, ' (罕见)\n防御 $1, 速度 $2\n'],
    [/^ \(uncommon\)\nDEF (.+), EVA (.+)\n$/, ' (罕见)\n防御 $1, 闪避 $2\n'],
    [/^ \(uncommon\)\nCRIT (.+), CRIT DMG (.+)\n$/, ' (罕见)\n暴击 $1, 暴击伤害 $2\n'],
    [/^ \(uncommon\)\nHP (.+)\n$/, ' (罕见)\n生命值 $1\n'],
    [/^ \(uncommon\)\nATK (.+)\n$/, ' (罕见)\n攻击 $1\n'],
    [/^ \(rare\)\nDEF (.+), EVA (.+)\n$/, ' (稀有)\n防御 $1, 闪避 $2\n'],
    [/^ \(rare\)\nDEF (.+), HP (.+)\n$/, ' (稀有)\n防御 $1, 生命值 $2\n'],
    [/^ \(rare\)\nDEF (.+), SPD (.+)\n$/, ' (稀有)\n防御 $1, 速度 $2\n'],
    [/^ \(rare\)\nHP (.+), CRIT DMG (.+)\n$/, ' (稀有)\n生命值 $1, 暴击伤害 $2\n'],
    [/^ \(rare\)\nATK (.+), CRIT DMG (.+)\n$/, ' (稀有)\n攻击 $1, 暴击伤害 $2\n'],
    [/^ \(rare\)\nCRIT (.+), CRIT DMG (.+)\n$/, ' (稀有)\n暴击 $1, 暴击伤害 $2\n'],
    [/^ \(rare\)\nATK (.+), CRIT (.+)\n$/, ' (稀有)\n攻击 $1, 暴击率 $2\n'],
    [/^ \(rare\)\nHP (.+)\n$/, ' (稀有)\n生命值 $1\n'],
    [/^ \(epic\)\nATK (.+), CRIT DMG (.+)\n$/, ' (史诗)\n攻击 $1, 暴击伤害 $2\n'],
    [/^ \(epic\)\nDEF (.+), HP (.+)\n$/, ' (史诗)\n防御 $1, 生命值 $2\n'],
    [/^ \(epic\)\nDEF (.+), SPD (.+)\n$/, ' (史诗)\n防御 $1, 速度 $2\n'],
    [/^ \(epic\)\nDEF (.+), EVA (.+)\n$/, ' (史诗)\n防御 $1, 闪避 $2\n'],
    [/^ \(epic\)\nATK (.+), CRIT DMG (.+)\n$/, ' (史诗)\n攻击 $1, 暴击伤害 $2\n'],
    [/^ \(epic\)\nATK (.+), CRIT (.+)\n$/, ' (史诗)\n攻击 $1, 暴击率 $2\n'],
    [/^ \(epic\)\nHP (.+)\n$/, ' (史诗)\n生命值 $1\n'],
    [/^ \(legendary\)\nDEF (.+), SPD (.+)\n$/, ' (传说)\n防御 $1, 速度 $2\n'],
    [/^ \(legendary\)\nHP (.+)\n$/, ' (传说)\n生命值 $1\n'],
    [/^ pet (.+) off at Floor (.+)$/, ' 宠物在 $2 层打折 $1'],
    [/^ hits you for (.+)!$/, ' 攻击了你并造成 $1 伤害!'],
    [/^Backstab! Critical hit for (.+)!$/, '背刺！暴击造成 $1 伤害!'],
    [/^ defeated! \+(.+) XP$/, ' 已击败! +$1 经验值'],
    [/^ shadow strikes for (.+)!$/, ' 暗影突袭 造成 $1 伤害!'],
    [/^You dodged (.+)\'s attack!$/, '你躲过了 $1 的攻击!'],
    [/^You hit Goblin for (.+).$/, '你攻击了 哥布林 并造成了 $1 伤害。'],
    [/^You hit Golem for (.+).$/, '你攻击了 魔像 并造成了 $1 伤害。'],
    [/^You hit Orc for (.+).$/, '你攻击了 兽人 并造成了 $1 伤害。'],
    [/^You hit Skeleton for (.+).$/, '你攻击了 骷髅 并造成了 $1 伤害。'],
    [/^You hit Dark Elf for (.+).$/, '你攻击了 暗精灵 并造成了 $1 伤害。'],
    [/^You hit Assassin for (.+).$/, '你攻击了 刺客 并造成了 $1 伤害。'],
    [/^You hit Necromancer for (.+).$/, '你攻击了 死灵法师 并造成了 $1 伤害。'],
    [/^You hit Guardian for (.+).$/, '你攻击了 守护者 并造成了 $1 伤害。'],
    [/^You hit Wraith for (.+).$/, '你攻击了 幽灵 并造成了 $1 伤害。'],
    [/^You hit Bat for (.+).$/, '你攻击了 老鼠 并造成了 $1 伤害。'],
    [/^You hit Demon for (.+).$/, '你攻击了 恶魔 并造成了 $1 伤害。'],
    [/^You hit Wolf for (.+).$/, '你攻击了 狼 并造成了 $1 伤害。'],
    [/^You hit Berserker for (.+).$/, '你攻击了 狂战士 并造成了 $1 伤害。'],
    [/^You hit Slime King for (.+).$/, '你攻击了 史莱姆之王 并造成了 $1 伤害。'],
    [/^You hit Slime for (.+).$/, '你攻击了 史莱姆 并造成了 $1 伤害。'],
    [/^You hit Vampire for (.+).$/, '你攻击了 吸血鬼 并造成了 $1 伤害。'],
    [/^You hit Zombie for (.+).$/, '你攻击了 僵尸 并造成了 $1 伤害。'],
    [/^You hit Snake for (.+).$/, '你攻击了 蛇 并造成了 $1 伤害。'],
    [/^You hit Spider for (.+).$/, '你攻击了 蜘蛛 并造成了 $1 伤害。'],
    [/^You hit Troll for (.+).$/, '你攻击了 巨魔 并造成了 $1 伤害。'],
    [/^You hit Rat for (.+).$/, '你攻击了 老鼠 并造成了 $1 伤害。'],
    [/^You hit Elite Goblin for (.+).$/, '你攻击了 精英哥布林 并造成了 $1 伤害。'],
    [/^You hit Elite Golem for (.+).$/, '你攻击了 精英魔像 并造成了 $1 伤害。'],
    [/^You hit Elite Orc for (.+).$/, '你攻击了 精英兽人 并造成了 $1 伤害。'],
    [/^You hit Elite Skeleton for (.+).$/, '你攻击了 精英骷髅 并造成了 $1 伤害。'],
    [/^You hit Elite Dark Elf for (.+).$/, '你攻击了 精英暗精灵 并造成了 $1 伤害。'],
    [/^You hit Elite Assassin for (.+).$/, '你攻击了 精英刺客 并造成了 $1 伤害。'],
    [/^You hit Elite Necromancer for (.+).$/, '你攻击了 精英死灵法师 并造成了 $1 伤害。'],
    [/^You hit Elite Guardian for (.+).$/, '你攻击了 精英守护者 并造成了 $1 伤害。'],
    [/^You hit Elite Wraith for (.+).$/, '你攻击了 精英幽灵 并造成了 $1 伤害。'],
    [/^You hit Elite Bat for (.+).$/, '你攻击了 精英老鼠 并造成了 $1 伤害。'],
    [/^You hit Elite Demon for (.+).$/, '你攻击了 精英恶魔 并造成了 $1 伤害。'],
    [/^You hit Elite Wolf for (.+).$/, '你攻击了 精英狼 并造成了 $1 伤害。'],
    [/^You hit Elite Berserker for (.+).$/, '你攻击了 精英狂战士 并造成了 $1 伤害。'],
    [/^You hit Elite Slime for (.+).$/, '你攻击了 精英史莱姆 并造成了 $1 伤害。'],
    [/^You hit Elite Vampire for (.+).$/, '你攻击了 精英吸血鬼 并造成了 $1 伤害。'],
    [/^You hit Elite Zombie for (.+).$/, '你攻击了 精英僵尸 并造成了 $1 伤害。'],
    [/^You hit Elite Snake for (.+).$/, '你攻击了 精英蛇 并造成了 $1 伤害。'],
    [/^You hit Elite Spider for (.+).$/, '你攻击了 精英蜘蛛 并造成了 $1 伤害。'],
    [/^You hit Elite Troll for (.+).$/, '你攻击了 精英巨魔 并造成了 $1 伤害。'],
    [/^You hit Elite Rat for (.+).$/, '你攻击了 精英老鼠 并造成了 $1 伤害。'],
    [/^Ice Spike hit (.+) for (.+).$/, '寒冰之刺 攻击了 $1 并造成了 $2 伤害。'],
    [/^Fireball hit (.+) for (.+).$/, '火球 攻击了 $1 并造成了 $2 伤害。'],
    [/^Fireball hits (.+) for (.+)!$/, '火球 攻击了 $1 并造成了 $2 伤害!'],
    [/^Magic blast hit (.+) for (.+).$/, '魔法爆炸 攻击了 $1 并造成了 $2 伤害。'],
    [/^Magic blast (.+) for (.+).$/, '魔法爆炸 对 $1 造成了 $2 伤害。'],
    [/^Jan ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 1 月 $1, $3:$4'],
    [/^Feb ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 2 月 $1, $3:$4'],
    [/^Mar ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 3 月 $1, $3:$4'],
    [/^Apr ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 4 月 $1, $3:$4'],
    [/^May ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 5 月 $1, $3:$4'],
    [/^Jun ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 6 月 $1, $3:$4'],
    [/^Jul ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 7 月 $1, $3:$4'],
    [/^Aug ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 8 月 $1, $3:$4'],
    [/^Sep ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 9 月 $1, $3:$4'],
    [/^Oct ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 10 月 $1, $3:$4'],
    [/^Nov ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 11 月 $1, $3:$4'],
    [/^Dec ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 12 月 $1, $3:$4'],
    [/^([\d\.]+)\/sec$/, '$1\/秒'],
    [/^([\d\.,]+)\/sec$/, '$1\/秒'],
    [/^([\d\.,]+) OOMs\/sec$/, '$1 OOMs\/秒'],
    [/^([\d\.]+) OOMs\/sec$/, '$1 OOMs\/秒'],
    [/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^([\d\.]+) elves$/, '$1 精灵'],
    [/^Soul Mult: ([\d\.]+)x \| Stat Mult: ([\d\.]+)x$/, '灵魂乘数: $1x | 属性乘数: $2x'],
    [/^\+([\d\.]+)\% elves$/, '+$1% 精灵'],
    [/^\+([\d\.]+)\% ATK when below ([\d\.]+)\% HP$/, '+$1% 攻击当生命值低于 $2%'],
    [/^\+([\d\.]+)\% All Stats$/, '+$1% 所有属性'],
    [/^\+([\d\.]+)\% Max HP$/, '+$1% 最大生命值'],
    [/^\+([\d\.]+)\% Crit Chance$/, '+$1% 暴击率'],
    [/^\+([\d\.]+)\% Legendary drops at 2000 kills$/, '在达到2000击杀时 +$1% 传说掉落'],
    [/^\+([\d\.]+)\% Speed$/, '+$1% 速度'],
    [/^\+([\d\.]+)\% Defense$/, '+$1% 防御'],
    [/^\+([\d\.]+)\% Attack$/, '+$1% 攻击'],
    [/^\+([\d\.]+)\% Evasion$/, '+$1% 闪避'],
    [/^\+([\d\.]+)\% All Stats!$/, '+$1% 所有属性!'],
    [/^\+([\d\.]+)\% HP, \+([\d\.]+)\% DEF$/, '+$1% 生命值, +$2% 防御'],
    [/^\+([\d\.]+)\% ATK, \+([\d\.]+)\% CRIT$/, '+$1% 攻击, +$2% 暴击'],
    [/^\+([\d\.]+)\% SPD, \+([\d\.]+)\% EVA$/, '+$1% 速度, +$2% 闪避'],
    [/^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m$/, '$1天 $2小时 $3分'],
    [/^([\d\.]+)h ([\d\.]+)m$/, '$1小时 $2分'],
    [/^([\d\.]+)m ([\d\.]+)s$/, '$1分钟 $2秒'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^([\d\.,]+) elves$/, '$1 精灵'],
    [/^([\d\.,]+)x damage, ([\d\.,]+) HP$/, '$1x 伤害, $2 生命值'],
    [/^([\d\.,]+) Soul Points$/, '$1 灵魂点数'],
    [/^([\d\.,]+) Soul Points, $/, '$1 灵魂点数, '],
    [/^([\d\.,]+) SP$/, '$1 灵魂点数'],
    [/^\(([\d\.,]+) SP\)$/, '($1 灵魂点数)'],
    [/^([\d\.,]+) SP \+ Equipment$/, '$1 灵魂点数 + 装备'],
    [/^([\d\.,]+) SP \+ Lucky Coin$/, '$1 灵魂点数 + 幸运币'],
    [/^([\d\.,]+) SP \+ Legendary Chest!$/, '$1 灵魂点数 + 传说宝箱!'],
    [/^! \+([\d\.,]+) SP$/, '! +$1 灵魂点数'],
    [/^\+([\d\.,]+) SP$/, '+$1 灵魂点数'],
    [/^\+([\d\.,]+) Adamantite$/, '+$1 艾德曼合金'],
    [/^\+([\d\.,]+) Mythril$/, '+$1 神话'],
    [/^\+([\d\.,]+) Max HP this run$/, '+$1 最大生命值本轮'],
    [/^\+([\d\.,]+) Boss Core$/, '+$1 Boss核心'],
    [/^\+([\d\.,]+) Monster Essence$/, '+$1 怪物精华'],
    [/^\+([\d\.,]+) Silver Ore$/, '+$1 银矿石'],
    [/^\+([\d\.,]+) Gold Ore$/, '+$1 金矿石'],
    [/^\+([\d\.,]+) Iron Ore$/, '+$1 铁矿石'],
    [/^\+([\d\.,]+) Dragon Scale$/, '+$1 龙鳞'],
    [/^Lv([\d\.,]+)$/, '等级 $1'],
    [/^You have fallen on Floor ([\d\.,]+)...$/, '你战败于楼层 $1...'],
    [/^Advancing to Floor ([\d\.,]+)...$/, '冒险前往楼层 $1...'],
    [/^Auto-continue in ([\d\.,]+)s$/, '$1 秒后自动继续'],
    [/^Skipped ([\d\.,]+) floors!$/, '跳过了 $1 楼层!'],
    [/^Floor ([\d\.,]+)$/, '层数 $1'],
    [/^LEVEL UP! You are now level ([\d\.,]+)!$/, '升级了! 你现在的等级是 $1!'],
    [/^Reach floor ([\d\.,]+)$/, '达到层数 $1'],
    [/^Reach floor ([\d\.,]+) in under ([\d\.,]+) minutes$/, '在 $2 分钟内达到层数 $1'],
    [/^Prestige ([\d\.,]+) times$/, '声望 $1 次'],
    [/^Land ([\d\.,]+) critical hits$/, '造成 $1 次暴击'],
    [/^Earn ([\d\.,]+) souls from chests$/, '从宝箱赚取 $1 灵魂'],
    [/^Earn ([\d\.,]+) souls total$/, '总计赚取 $1 灵魂'],
    [/^Die ([\d\.,]+) times$/, '死亡 $1 次'],
    [/^Kill ([\d\.,]+) monsters$/, '击杀 $1 怪物'],
    [/^Kill ([\d\.,]+) elite monsters$/, '击杀 $1 精英怪物'],
    [/^Upgrade weapons ([\d\.,]+) times$/, '升级 $1 次武器'],
    [/^Defeat ([\d\.,]+) bosses$/, '击败 $1 Boss'],
    [/^Defeat ([\d\.,]+) elites$/, '击败 $1 精英'],
    [/^Deal ([\d\.,]+) total damage$/, '造成 $1 总伤害'],
    [/^Buy ([\d\.,]+) items from merchants$/, '从商人那里购买 $1 物品'],
    [/^Trigger ([\d\.,]+) traps and survive$/, '触发 $1 陷阱并存活'],
    [/^Open ([\d\.,]+) chests$/, '打开 $1 宝箱'],
    [/^Find ([\d\.,]+) legendary items$/, '发现 $1 传说物品'],
    [/^Use ([\d\.,]+) altars$/, '使用 $1 祭坛'],
    [/^Use ([\d\.,]+) fountains$/, '使用 $1 喷泉'],
    [/^Use ([\d\.,]+) shrines$/, '使用 $1 神殿'],
    [/^relic\_slot\_([\d\.,]+)$/, '遗物槽位 $1'],
    [/^Day ([\d\.,]+)$/, '天数 $1'],
    [/^level ([\d\.,]+) \/ ([\d\.,]+)$/, '等级 $1 \/ $2'],
    [/^level: ([\d\.,]+) \/ ([\d\.,]+)$/, '等级 $1 \/ $2'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^Login Streak: (.+) days$/, '连续登录：$1 天'],
    [/^Reward: (.+) SP$/, '奖励：$1 灵魂点数'],
    [/^Reward: (.+) SP \+ Relic$/, '奖励：$1 灵魂点数 + 遗物'],
    [/^Cost: (.+) points$/, '成本：$1 点数'],
    [/^Req: (.+) elves$/, '要求：$1 精灵'],
    [/^Req: (.+) \/ (.+) elves$/, '要求：$1 \/ $2 精灵'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);