/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com
 @idle games : http://www.gityx.com
 @QQ Group : 627141737

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置得到 + ",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Goal:": "目标:",
    "Reward": "奖励",
    "Start": "开始",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Milestone Gotten!": "获得里程碑！",
    "Milestones": "里程碑",
    "Completed": "已完成",
    "Default Save": "默认存档",
    "Delete": "删除",
    "No": "否",
    "Saves": "存档",
    "Options": "选项",
    "Yes": "是",
    "Are you sure?": "你确定吗？",
    "Edit Name": "编辑名称",
    "Info": "信息",
    "Currently:": "当前:",
    "Appearance": "外观",
    "How the game looks.": "游戏看起来如何。",
    "Theme": "主题",
    "Show milestones": "显示里程碑",
    "Show TPS meter at the bottom-left corner of the page.": "在页面左下角显示 TPS。",
    "Show TPS": "显示 TPS",
    "None": "无",
    "Align modifier units": "对齐概览单位",
    "Align numbers to the beginning of the unit in modifier view.": "在概览视图中将数字与单元的开头对齐。",
    "Select which milestones to display based on criterias.": "根据标准选择要显示的里程碑。",
    "All": "全部",
    "Classic": "经典",
    "Configurable": "可配置",
    "Duplicate": "复制",
    "Mute": "静音",
    "Unmute": "播放",
    "Join the Discord!": "加入 Discord!",
    "Fix export button and save": "修复导出按钮和保存",
    "ENABLED": "启用",
    "Export to file": "导出为文件",
    "Import clipboard": "从剪贴板导入",
    "Import file": "从文件导入",
    "DISABLED": "禁用",
    "Experience": "经验值",
    "Speed": "速度",
    "Skills": "技能",
    "Skip": "跳过",
    "Souls": "灵魂",
    "Soul Shop": "灵魂商店",
    "Soul Points": "灵魂点数",
    "Soul Points Earned:": "赚取的灵魂点数:",
    "Souls on Prestige:": "声望获得灵魂:",
    "Sound FX": "音效",
    "Sound Effects": "声音效果",
    "Fireball": "火球",
    "Skill Tree": "技能树",
    "Shop": "商店",
    "Show Combat Log": "显示战斗日志",
    "Save Data": "保存数据",
    "PRESTIGE": "声望",
    "Prestige": "声望",
    "Next": "下一个",
    "Pets": "宠物",
    "New Multiplier:": "新乘数:",
    "New Game": "新游戏",
    "Music": "音乐",
    "Music Volume": "音乐音量",
    "More": "更多",
    "Monsters Killed:": "击杀怪物:",
    "Merchant": "商人",
    "Max HP": "最大生命值",
    "Max offline time is 8 hours": "最大离线时间是8小时",
    "Mage": "法师",
    "RUNNER": "奔跑者",
    "Lv.": "等级",
    "Locked": "未解锁",
    "Made by ZombieCoco 🧟": "作者 ZombieCoco 🧟",
    "Life Crystal": "生命水晶",
    "Items": "物品",
    "Inventory": "库存",
    "Import Save": "导入存档",
    "IDLE": "放置",
    "Idle Dungeon Runner": "放置地牢奔跑者",
    "HP": "生命值",
    "Level": "等级",
    "Leave": "离开",
    "Keyboard Shortcuts": "键盘快捷键",
    "Level Reached:": "达到等级:",
    "Reset All": "重置所有",
    "Relics": "遗物",
    "Stats": "属性",
    "Stats |": "属性 |",
    "Status Effects": "状态效果",
    "💰 Sell Common": "💰 出售普通",
    "⬆️ Equip Best": "⬆️ 装备最佳",
    "Crit %": "暴击 %",
    "Display": "显示",
    "Defense": "防御",
    "Crit DMG": "暴击伤害",
    "Copy": "复制",
    "Continue": "继续",
    "Combat Log": "战斗日志",
    "Close": "关闭",
    "DUNGEON": "地牢",
    "Dungeon Depths": "地牢深度",
    "Claim Rewards": "领取奖励",
    "Earned:": "获得:",
    "Empty": "空",
    "Equip": "装备",
    "Endless Adventure Awaits": "无尽的冒险等待着你",
    "Effect description": "效果描述",
    "Daily Reward Available!": "每日奖励可用!",
    "Equipment": "装备",
    "Equipment |": "装备 |",
    "Export Save": "导出存档",
    "Evasion": "闪避",
    "Floor": "层数",
    "Floor Reached:": "达到层数:",
    "Guardian Shield": "守护之盾",
    "Hero Stats": "英雄属性",
    "High Speed & Evasion": "高速度 & 闪避",
    "High HP & Defense": "高生命值 & 防御",
    "High Damage & Crit": "高伤害 & 暴击",
    "Use Skills": "使用技能",
    "Unlocked:": "已解锁:",
    "Warrior": "战士",
    "Warrior's Blade": "战士之刃",
    "Weapon": "武器",
    "Welcome Back!": "欢迎回来!",
    "Welcome!": "欢迎!",
    "Welcome, adventurer!": "欢迎, 冒险者!",
    "XP:": "经验值:",
    "You Have Fallen!": "你失败了！",
    "You were away for": "你离开了",
    "Tutorial text here": "这是教程文本",
    "Toggle Speed": "切换速度",
    "Treasure Found!": "发现宝藏!",
    "Take All": "全部拿走",
    "Synergy": "协同",
    "Best": "最佳",
    "Audio": "音频",
    "Ascend": "转生",
    "Ascension": "转生",
    "Armor": "护甲",
    "Attack": "攻击",
    "Auto-equip better gear": "自动穿戴更好的装备",
    "Challenge": "挑战",
    "Choose Your Class": "选择你的职业",
    "Accessory": "配饰",
    "Achieve": "成就",
    "Achievement Unlocked!": "成就解锁！",
    "Activate": "激活",
    "Active Skills": "主动技能",
    "Active:": "主动：",
    "Ancient Shrine": "上古神殿",
    "Choose Your Class": "选择你的课程",
    "Companions that follow and assist you!": "跟随和帮助你的同伴！",
    "Complete challenges for Soul Points and Relics!": "完成灵魂点数和圣物的挑战！",
    "Current Multiplier:": "当前乘数:",
    "Equip relics for powerful passive bonuses!": "装备圣物获得强大的被动加成！",
    "Hold button to buy multiple": "按住按钮购买多个",
    "Keeps: Soul Upgrades, Special Items, Achievements": "保留：灵魂升级，特殊物品，成就",
    "Milestone Unlocked!": "里程碑解锁!",
    "No active synergies. Combine class, pet, and equipment for bonuses!": "没有活跃的协同效应。职业、宠物、装备组合可获得加成！",
    "No relics found yet. Complete challenges or reach milestones!": "还没有发现任何遗物。完成挑战或达到里程碑！",
    "Prestige to gain permanent multipliers!": "声望获得永久乘数!",
    "Reach new heights of power!": "达到新的高度的力量!",
    "Resets: Floor, Level, Equipment, Run Stats": "重置：楼层，等级，装备，运行状态",
    "Rise Again": "东山再起",
    "Rogue": "流氓",
    "Shadow Cloak": "暗影披风",
    "Show Damage Numbers": "显示伤害数字",
    "Show Particles": "显示粒子",
    "Shadow Step": "影步",
    "Whirlwind": "旋风",
    "Space": "空间",
    "Statistics Dashboard": "统计面板",
    "Swift Boots": "迅捷长靴",
    "Synergies activate when conditions are met": "当条件满足时，协同作用就会启动",
    " is poisoned!": " 中毒了!",
    "You is poisoned!": "你中毒了!",
    "Warrior ⚔️": "战士 ⚔️",
    " dropped Uncommon Robes!": "掉落了 罕见的长袍!",
    "Unlock all pets": "解锁所有宠物",
    "Treasure Hunter": "宝藏猎人",
    "Treasure Master": "宝藏大师",
    "Total Souls": "总计灵魂",
    "Total Runs": "总运行次数",
    "Total Damage": "总伤害",
    "Regen 2% HP/sec": "恢复 2% 生命值/秒",
    "Mage 🔮": "法师 🔮",
    "MINI-BOSS": "迷你BOSS",
    "Monster Slayer": "怪物杀手",
    "Lightning": "雷电",
    "Legendary Collector": "传说收集者",
    "Legendary Find": "传说发现",
    "Legendaries": "传说",
    "Legend of the Dungeon": "地牢传说",
    "Heal": "治疗",
    "Getting Started": "入门",
    "Highest Hit": "最高命中",
    "Get healed 10 times": "获得 10 次治疗",
    "Spawning...": "重生中...",
    "Soul Vault": "灵魂金库",
    "Soul Banker": "灵魂银行家",
    "Soul Treasury": "灵魂宝藏",
    "Soul Saver": "灵魂拯救者",
    "Time Played": "游戏时长",
    "Morning": "早上",
    "Noon": "中午",
    "Dawn": "黎明",
    "Trap Survivor": "陷阱幸存者",
    "Trap Veteran": "陷阱老兵",
    "Open!": "打开!",
    "Elite Hunter": "精英猎人",
    "Elite Slayer": "精英杀手",
    "Monsters Killed": "击杀怪物",
    "Elite Killed": "击杀精英",
    "Kill your first monster": "击杀第一只怪物",
    "Mystic Owl": "神话猫头鹰",
    "A new adventure begins...": "一场新的冒险开始了...",
    "Abyss Walker": "深渊行者",
    "All monsters defeated! An exit portal has appeared!": "所有怪物都被打败了！出现了出口传送门！",
    "Ancient Turtle": "古老的乌龟",
    "Apocalypse": "天启",
    "Arcane Shield": "奥术之盾",
    "Artifact Hoarder": "神兵囤积者",
    "Ascended": "升天",
    "Uncommon Bracelet!": "罕见的手镯！",
    "Avg Floor/Run": "平均楼层/运行",
    "Baby Phoenix": "凤凰宝宝",
    "Backstab": "背刺",
    "Battle Cry": "战斗呐喊",
    "Best Floor": "最佳楼层",
    "Better Boss loot at 25 boss kills": "在杀死25个Boss时获得更好的Boss战利品",
    "Blessed": "祝福",
    "Boss Destroyer": "Boss破坏者",
    "Boss Hunter": "Boss猎人",
    "Boss Slayer": "Boss杀手",
    "Bosses Slain": "击杀首领",
    "Chests Opened": "宝箱开启次数",
    "Claim Reward!": "领取奖励！",
    "Come back tomorrow!": "明天再来吧！",
    "Critical Mass": "暴击批量",
    "Critical Master": "暴击大师",
    "Damage Dealer": "伤害经销商",
    "Dash": "冲刺",
    "Dashed away!": "跑掉了！",
    "Death Incarnate": "死亡化身",
    "Deep Delver": "深度挖掘",
    "Defeat a boss": "打败一个boss",
    "Defeat an elite monster": "打败一个精英怪物",
    "Devastator": "毁灭者",
    "Die for the first time": "第一次死亡",
    "DODGE": "闪避",
    "Drake Hatchling": "龙兽幼崽",
    "Dungeon Explorer": "地牢探险家",
    "Dungeon Master": "地牢大师",
    "Elite Eradicator": "精英根除者",
    "Eternal": "永恒",
    "Exterminator": "灭虫者",
    "Forged in Fire": "烈火锻造",
    "Frequent Patient": "常客",
    "Frost Assassin": "冰霜刺客",
    "Frozen enemies take +50% crit damage": "冰冻敌人受到+50%的暴击伤害",
    "Gambler": "赌徒",
    "Hoarder": "囤积狂",
    "Ice Spike": "寒冰之刺",
    "More Elite spawns at 500 kills": "500击杀时生成更多精英",
    "Never Give Up": "永不放弃",
    "No accessory equipped": "暂未装备饰品",
    "No armor equipped": "没有装备盔甲",
    "No better items to equip.": "没有更好的装备了。",
    "No common items to sell.": "暂无可出售的普通道具",
    "No weapon equipped": "没有装备武器",
    "Persistent": "持续的",
    "Pet Collector": "宠物收藏家",
    "Pet Owner": "宠物主人",
    "Poison Blade": "毒刃",
    "Prestige for the first time": "第一次获得声望",
    "Quick Descent": "速降",
    "Rat dropped Common Hammer!": "老鼠掉了普通的锤子！",
    "Reborn": "重生",
    "Refreshed": "已刷新",
    "Rogue 🗡️": "流氓 🗡️",
    "ROOTED!": "扎根!",
    "Shadow Wolf": "暗影狼",
    "Shield Bash": "盾击",
    "Shopaholic": "购物狂",
    "Smoke Bomb": "烟雾弹",
    "Speed Runner": "竞速者",
    "Synergies activate when conditions are met!": "当条件满足时，协同作用就会激活！",
    "Transcendent": "超凡脱俗",
    "Treasure Seeker": "寻宝者",
    "Triggered Boulder Trap! Massive damage and knockback": "触发巨石陷阱！大量伤害和击退",
    "Triggered Poison Gas! Releases poison gas for 5 seconds": "触发毒气！释放毒气，持续5秒",
    "Triggered Spider Web! Immobilizes for 3 seconds": "触发蜘蛛网！定身3秒",
    "Undying Spirit": "不朽的灵魂",
    "Universal ⚔️": "万能⚔️",
    "Unlock 2nd Relic Slot at Floor 50": "在第50层解锁第2个遗物槽",
    "Unlock Ascension at Prestige 5": "在声望5解锁转生",
    "Unlock Challenge Modes at Floor 25": "在25层解锁挑战模式",
    "Unlock Endless Mode at Floor 100": "在100层解锁无尽模式",
    "Unlock your first pet": "解锁你的第一个宠物",
    "Veteran Bonus after 1 hour played": "1个小时后的老兵奖励",
    "Thunderstorm": "雷雨",
    " Rage": "狂怒",
    "Attack Potion (+25% ATK, 60s) - 20 SP": "攻击药水（+25%攻击力，持续60秒）- 20 灵魂点数",
    "Defense Potion (+25% DEF, 60s) - 20 SP": "防御药剂（+25%防御，持续60秒）- 20 灵魂点数",
    "Elites Killed": "击杀精英",
    "Find a legendary item": "发现一个传说物品",
    "Health Potion (Heal 30%) - 10 SP": "生命药水（治疗30%）- 10 灵魂点数",
    "Speed Potion (+30% SPD, 60s) - 15 SP": "加速药水（+30% 速度， 持续60秒）- 15 灵魂点数",
    "Traveling Merchant": "旅行商人",
    "Want to buy something?": "想买点东西吗？",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "SP": "灵魂点数",
    // 图标代码，不能汉化
    "Jacorb's Games": "Jacorb's Games",
    "/": "/",
    "×": "×",
    "▶️": "▶️",
    "★": "★",
    "⚔️": "⚔️",
    "⚙️": "⚙️",
    "🌀": "🌀",
    "🎮": "🎮",
    "💀": "💀",
    "💎": "💎",
    "💚": "💚",
    "💨": "💨",
    "📊": "📊",
    "📦": "📦",
    "🔥": "🔥",
    "🚪": "🚪",
    "🛒": "🛒",
    "🛡️": "🛡️",
    "?": "?",
    "⌚": "⌚",
    "⚡": "⚡",
    "👘": "👘",
    "👤": "👤",
    "💍": "💍",
    "📢": "📢",
    "🔨": "🔨",
    "🔮": "🔮",
    "🗡️": "🗡️",
    "🧊": "🧊",
    "🧪": "🧪",
    "😤": "😤",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "+": "+",
    ".": ".",
    "…": "…",
    ":": ":",
    "-": "-",
    "|": "|",
    "(": "(",
    ")": ")",
    "Scientific": "科学计数法",
    "Standard": "标准",
    "Blind": "盲文",
    "Letters": "字母",
    "Mixed Engineering": "混合工程",
    "Mixed Scientific": "混合科学",
    "Chemistry": "化学",
    "Engineering": "工程符号",
    "By Jacorb90": "By Jacorb90",
    "content_copy": "content_copy",
    "library_books": "library_books",
    "discord": "discord",
    "drag_handle": "drag_handle",
    "edit": "edit",
    "forum": "forum",
    "content_paste": "content_paste",
    "delete": "delete",
    "info": "info",
    "settings": "settings",
    'Twitter': 'Twitter',
    "Discord": "Discord",
    "Facebook": "Facebook",
    "Instagram": "Instagram",
    "gityxcom": "gityxcom",
    "Footer": "Footer",
    "Wiki": "Wiki",
    "gityx": "gityx",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    'Gityx游戏': 'Gityx游戏',
    'Git游戏': 'Git游戏',
    'QQ群号': 'QQ群号',
    'x': 'x',
    'QQ群号:': 'QQ群号:',
    '* 启用后台游戏': '* 启用后台游戏',
    '更多同类游戏:': '更多同类游戏:',
    'i': 'i',
    'I': 'I',
    'II': 'II',
    'III': 'III',
    'IV': 'IV',
    'V': 'V',
    'VI': 'VI',
    'VII': 'VII',
    'VIII': 'VIII',
    'X': 'X',
    'XI': 'XI',
    'XII': 'XII',
    'XIII': 'XIII',
    'XIV': 'XIV',
    'XV': 'XV',
    'XVI': 'XVI',
    'A': 'A',
    'B': 'B',
    'C': 'C',
    'D': 'D',
    'E': 'E',
    'F': 'F',
    'G': 'G',
    'H': 'H',
    'I': 'I',
    'J': 'J',
    'K': 'K',
    'L': 'L',
    'M': 'M',
    'N': 'N',
    'O': 'O',
    'P': 'P',
    'Q': 'Q',
    'R': 'R',
    'S': 'S',
    'T': 'T',
    'U': 'U',
    'V': 'V',
    'W': 'W',
    'X': 'X',
    'Y': 'Y',
    'Z': 'Z',
    'a': 'a',
    'b': 'b',
    'c': 'c',
    'd': 'd',
    'e': 'e',
    'f': 'f',
    'g': 'g',
    'h': 'h',
    'i': 'i',
    'j': 'j',
    'k': 'k',
    'l': 'l',
    'm': 'm',
    'n': 'n',
    'o': 'o',
    'p': 'p',
    'q': 'q',
    'r': 'r',
    's': 's',
    't': 't',
    'u': 'u',
    'v': 'v',
    'w': 'w',
    'x': 'x',
    'y': 'y',
    'z': 'z',
    '<': '<',
    '<<': '<<',
    '>': '>',
    '>>': '>>',
    'Jan': '1月',
    'Feb': '2月',
    'Mar': '3月',
    'Apr': '4月',
    'May': '5月',
    'Jun': '6月',
    'Jul': '7月',
    'Aug': '8月',
    'Sep': '9月',
    'Oct': '10月',
    'Nov': '11月',
    'Dec': '12月',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',

}


//需处理的前缀，此处可以截取语句开头部分的内容进行汉化
//例如：Coin: 13、Coin: 14、Coin: 15... 这种有相同开头的语句
//可以在这里汉化开头："Coin: ":"金币: "
var cnPrefix = {
    "\n": "\n",
    "                   ": "                   ",
    "                  ": "                  ",
    "                 ": "                 ",
    "                ": "                ",
    "               ": "               ",
    "              ": "              ",
    "             ": "             ",
    "            ": "            ",
    "           ": "           ",
    "          ": "          ",
    "         ": "         ",
    "        ": "        ",
    "       ": "       ",
    "      ": "      ",
    "     ": "     ",
    "    ": "    ",
    "   ": "   ",
    "  ": "  ",
    " ": " ",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Shift-Click to Toggle Tooltips: ": "Shift-单击以切换工具提示：",
    "Notation: ": "符号: ",
    "Toggle Music: ": "切换声音: ",
    "Animations: ": "动画: ",
    "Current Endgame: ": "当前终局: ",
    "Space Background: ": "太空背景: ",
    "Skill: ": "技能: ",
    "Version ": "版本 ",
    "Zombie": "僵尸",
    "Rat": "老鼠",
    "Orc": "兽人",
    "Golem": "魔像",
    "Goblin": "哥布林",
    "Achievement: ": "成就: ",
    "Berserker": "狂战士",
    "CRIT! ": "暴击! ",
    "Time: ": "时间: ",
    "Troll": "巨魔",
    "Skeleton": "骷髅",
    "Wolf": "狼",
    "Snake": "蛇",
    "Spider": "蜘蛛",
    "Auto-equipped ": "自动装备 ",
    "Common Hammer": "普通的锤子",
    "Uncommon Robes": "罕见的长袍",
    "Opened chest! Found ": "打开宝箱! 发现 ",
    "Uncommon Bracelet": "罕见的手镯",
    "First Death": "第一条命",
    "First Blood": "第一滴血",
    "Weather changed to: ": "天气转变为：",
    "Vampire": "吸血鬼",
    "Slime": "史莱姆",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀，此处可以截取语句结尾部分的内容进行汉化
//例如：13 Coin、14 Coin、15 Coin... 这种有相同结尾的语句
//可以在这里汉化结尾：" Coin":" 金币"
var cnPostfix = {
    "                   ": "                   ",
    "                  ": "                  ",
    "                 ": "                 ",
    "                ": "                ",
    "               ": "               ",
    "              ": "              ",
    "             ": "             ",
    "            ": "            ",
    "           ": "           ",
    "          ": "          ",
    "         ": "         ",
    "        ": "        ",
    "       ": "       ",
    "      ": "      ",
    "     ": "     ",
    "    ": "    ",
    "   ": "   ",
    "  ": "  ",
    " ": " ",
    "\n": "\n",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "/sec)": "/秒)",
    ' I': ' I',
    ' II': ' II',
    ' III': ' III',
    ' IV': ' IV',
    ' V': ' V',
    ' VI': ' VI',
    ' VII': ' VII',
    ' VIII': ' VIII',
    ' X': ' X',
    ' XI': ' XI',
    ' XII': ' XII',
    ' XIII': ' XIII',
    ' XIV': ' XIV',
    ' XV': ' XV',
    ' XVI': ' XVI',
    "[Tap to unequip]": "[点击脱下]",
    "[Tap to equip]": "[点击穿上]",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)h$/,
    /^([\d\.]+)m$/,
    /^([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)y ([\d\.]+)d ([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)y ([\d\.]+)d ([\d\.]+)h$/,
    /^([\d\.]+)\-([\d\.]+)\-([\d\.]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)$/,
    /^×([\d\.]+)$/,
    /^x([\d\.]+)$/,
    /^v([\d\.]+)$/,
    /^\$([\d\.]+)$/,
    /^\(([\d\.]+)\)$/,
    /^([\d\.]+)\%$/,
    /^\+([\d\.]+)\%$/,
    /^\-([\d\.]+)\%$/,
    /^([\d\.]+)\/([\d\.]+)$/,
    /^\-([\d\.]+)\/([\d\.]+)$/,
    /^([\d\.]+)\/([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.,]+)$/,
    /^([\d\.,]+)\-([\d\.,]+)$/,
    /^\(([\d\.]+)\/([\d\.]+)\)$/,
    /^\(([\d\.]+),([\d\.]+)\)$/,
    /^\(\-([\d\.]+),([\d\.]+)\)$/,
    /^\(\-([\d\.]+),\-([\d\.]+)\)$/,
    /^\(([\d\.]+),\-([\d\.]+)\)$/,
    /^成本(.+)$/,
    /^\(([\d\.]+)\%\)$/,
    /^\[([\d\.]+)\]$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)\-([\d\.]+)\-([\d\.]+) ([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^\[([\d\.]+):([\d\.]+):([\d\.]+)\]$/,
    /^([\d\.]+)K$/,
    /^([\d\.]+)M$/,
    /^([\d\.]+)B$/,
    /^([\d\.]+) K$/,
    /^([\d\.]+) M$/,
    /^([\d\.]+) B$/,
    /^([\d\.]+) T$/,
    /^([\d\.]+) Qi$/,
    /^([\d\.]+) Qa$/,
    /^([\d\.]+) Sp$/,
    /^([\d\.]+) Oc$/,
    /^([\d\.]+) Dc$/,
    /^([\d\.]+) UDc$/,
    /^([\d\.]+) No$/,
    /^([\d\.]+) Sx$/,
    /^([\d\.]+) QaDc$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^x([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^\$([\d\.,]+)$/,
    /^\+([\d\.,]+)$/,
    /^\-([\d\.,]+)$/,
    /^([\d\.,]+)x$/,
    /^x([\d\.,]+)$/,
    /^×([\d\.,]+)$/,
    /^([\d\.,]+) \/ ([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+) \/ ([\d\.]+)e([\d\.,]+)$/,
    /^\$([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e\+([\d\.,]+)$/,
    /^e([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    // /^([\uD800-\uDBFF][\uDC00-\uDFFF])|([\u2600-\u27BF])|([\u2300-\u23FF])|([\u2B50-\u2B55])|([\u203C-\u3299])|[\u21A9\u21AA\u25B6\u25C0\u2B06\u2B07\u2B05\u2B95\u2B99\u2B9A]+$/,
    // /^([\uD800-\uDBFF][\uDC00-\uDFFF])|([\u2600-\u27BF])|([\u2300-\u23FF])|([\u2B50-\u2B55])|([\u203C-\u3299])+$/,
    // /^[\uD800-\uFFFF]+$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//字母加数字：([\d\.]+[A-Za-z])
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
//&nbsp;空格：\xA0
var cnRegReplace = new Map([
    [/^([\d\.]+) hours ([\d\.]+) minutes ([\d\.]+) seconds$/, '$1 小时 $2 分钟 $3 秒'],
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
    [/^Daily Reward Day (.+): (.+) Soul Points$/, '每日奖励第 $1 天：$2 灵魂点数'],
    [/^Healed for (.+) HP!$/, '治疗了 $1 生命值!'],
    [/^ \(common\)\nATK (.+), SPD (.+)\n$/, ' (普通)\n攻击 $1, 速度 $2\n'],
    [/^ \(uncommon\)\nDEF (.+), HP (.+)\n$/, ' (罕见)\n防御 $1, 生命值 $2\n'],
    [/^ pet (.+) off at Floor (.+)$/, ' 宠物在 $2 层打折 $1'],
    [/^ hits you for (.+)!$/, ' 攻击了你并造成 $1 伤害!'],
    [/^ defeated! \+(.+) XP$/, ' 已击败! +$1 经验值'],
    [/^You dodged (.+)\'s attack!$/, '你躲过了 $1 的攻击!'],
    [/^You hit Goblin for (.+).$/, '你攻击了 哥布林 并造成了 $1 伤害。'],
    [/^You hit Golem for (.+).$/, '你攻击了 魔像 并造成了 $1 伤害。'],
    [/^You hit Orc for (.+).$/, '你攻击了 兽人 并造成了 $1 伤害。'],
    [/^You hit Skeleton for (.+).$/, '你攻击了 骷髅 并造成了 $1 伤害。'],
    [/^You hit Wolf for (.+).$/, '你攻击了 狼 并造成了 $1 伤害。'],
    [/^You hit Berserker for (.+).$/, '你攻击了 狂战士 并造成了 $1 伤害。'],
    [/^You hit Slime for (.+).$/, '你攻击了 史莱姆 并造成了 $1 伤害。'],
    [/^You hit Vampire for (.+).$/, '你攻击了 吸血鬼 并造成了 $1 伤害。'],
    [/^You hit Zombie for (.+).$/, '你攻击了 僵尸 并造成了 $1 伤害。'],
    [/^You hit Snake for (.+).$/, '你攻击了 蛇 并造成了 $1 伤害。'],
    [/^You hit Spider for (.+).$/, '你攻击了 蜘蛛 并造成了 $1 伤害。'],
    [/^You hit Troll for (.+).$/, '你攻击了 巨魔 并造成了 $1 伤害。'],
    [/^You hit Rat for (.+).$/, '你攻击了 老鼠 并造成了 $1 伤害。'],
    [/^Jan ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 1 月 $1, $3:$4'],
    [/^Feb ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 2 月 $1, $3:$4'],
    [/^Mar ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 3 月 $1, $3:$4'],
    [/^Apr ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 4 月 $1, $3:$4'],
    [/^May ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 5 月 $1, $3:$4'],
    [/^Jun ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 6 月 $1, $3:$4'],
    [/^Jul ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 7 月 $1, $3:$4'],
    [/^Aug ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 8 月 $1, $3:$4'],
    [/^Sep ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 9 月 $1, $3:$4'],
    [/^Oct ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 10 月 $1, $3:$4'],
    [/^Nov ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 11 月 $1, $3:$4'],
    [/^Dec ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 12 月 $1, $3:$4'],
    [/^([\d\.]+)\/sec$/, '$1\/秒'],
    [/^([\d\.,]+)\/sec$/, '$1\/秒'],
    [/^([\d\.,]+) OOMs\/sec$/, '$1 OOMs\/秒'],
    [/^([\d\.]+) OOMs\/sec$/, '$1 OOMs\/秒'],
    [/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^([\d\.]+) elves$/, '$1 精灵'],
    [/^\+([\d\.]+)\% elves$/, '+$1% 精灵'],
    [/^\+([\d\.]+)\% ATK when below ([\d\.]+)\% HP$/, '+$1% 攻击当生命值低于 $2%'],
    [/^\+([\d\.]+)\% All Stats$/, '+$1% 所有属性'],
    [/^\+([\d\.]+)\% Max HP$/, '+$1% 最大生命值'],
    [/^\+([\d\.]+)\% Crit Chance$/, '+$1% 暴击率'],
    [/^\+([\d\.]+)\% Legendary drops at 2000 kills$/, '在达到2000击杀时 +$1% 传说掉落'],
    [/^\+([\d\.]+)\% Speed$/, '+$1% 速度'],
    [/^\+([\d\.]+)\% Defense$/, '+$1% 防御'],
    [/^\+([\d\.]+)\% Attack$/, '+$1% 攻击'],
    [/^\+([\d\.]+)\% Evasion$/, '+$1% 闪避'],
    [/^\+([\d\.]+)\% HP, \+([\d\.]+)\% DEF$/, '+$1% 生命值, +$2% 防御'],
    [/^\+([\d\.]+)\% ATK, \+([\d\.]+)\% CRIT$/, '+$1% 攻击, +$2% 暴击'],
    [/^\+([\d\.]+)\% SPD, \+([\d\.]+)\% EVA$/, '+$1% 速度, +$2% 闪避'],
    [/^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m$/, '$1天 $2小时 $3分'],
    [/^([\d\.]+)h ([\d\.]+)m$/, '$1小时 $2分'],
    [/^([\d\.]+)m ([\d\.]+)s$/, '$1分钟 $2秒'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^([\d\.,]+) elves$/, '$1 精灵'],
    [/^([\d\.,]+) Soul Points$/, '$1 灵魂点数'],
    [/^([\d\.,]+) Soul Points, Uncommon Bracelet$/, '$1 灵魂点数, 罕见的手镯'],
    [/^([\d\.,]+) SP$/, '$1 灵魂点数'],
    [/^([\d\.,]+) SP \+ Equipment$/, '$1 灵魂点数 + 装备'],
    [/^([\d\.,]+) SP \+ Lucky Coin$/, '$1 灵魂点数 + 幸运币'],
    [/^([\d\.,]+) SP \+ Legendary Chest!$/, '$1 灵魂点数 + 传说宝箱!'],
    [/^! \+([\d\.,]+) SP$/, '! +$1 灵魂点数'],
    [/^\+([\d\.,]+) SP$/, '+$1 灵魂点数'],
    [/^\+([\d\.,]+) Monster Essence$/, '+$1 怪物精华'],
    [/^\+([\d\.,]+) Silver Ore$/, '+$1 银矿石'],
    [/^Lv([\d\.,]+)$/, '等级 $1'],
    [/^You have fallen on Floor ([\d\.,]+)...$/, '你战败于楼层 $1...'],
    [/^Advancing to Floor ([\d\.,]+)...$/, '冒险前往楼层 $1...'],
    [/^Auto-continue in ([\d\.,]+)s$/, '$1 秒后自动继续'],
    [/^Floor ([\d\.,]+)$/, '层数 $1'],
    [/^LEVEL UP! You are now level ([\d\.,]+)!$/, '升级了! 你现在的等级是 $1!'],
    [/^Reach floor ([\d\.,]+)$/, '达到层数 $1'],
    [/^Reach floor ([\d\.,]+) in under ([\d\.,]+) minutes$/, '在 $2 分钟内达到层数 $1'],
    [/^Prestige ([\d\.,]+) times$/, '声望 $1 次'],
    [/^Land ([\d\.,]+) critical hits$/, '造成 $1 次暴击'],
    [/^Earn ([\d\.,]+) souls from chests$/, '从宝箱赚取 $1 灵魂'],
    [/^Earn ([\d\.,]+) souls total$/, '总计赚取 $1 灵魂'],
    [/^Die ([\d\.,]+) times$/, '死亡 $1 次'],
    [/^Kill ([\d\.,]+) monsters$/, '击杀 $1 怪物'],
    [/^Upgrade weapons ([\d\.,]+) times$/, '升级 $1 次武器'],
    [/^Defeat ([\d\.,]+) bosses$/, '击败 $1 Boss'],
    [/^Defeat ([\d\.,]+) elites$/, '击败 $1 精英'],
    [/^Deal ([\d\.,]+) total damage$/, '造成 $1 总伤害'],
    [/^Buy ([\d\.,]+) items from merchants$/, '从商人那里购买 $1 物品'],
    [/^Trigger ([\d\.,]+) traps and survive$/, '触发 $1 陷阱并存活'],
    [/^Open ([\d\.,]+) chests$/, '打开 $1 宝箱'],
    [/^Find ([\d\.,]+) legendary items$/, '发现 $1 传说物品'],
    [/^Use ([\d\.,]+) altars$/, '使用 $1 祭坛'],
    [/^Use ([\d\.,]+) fountains$/, '使用 $1 喷泉'],
    [/^Use ([\d\.,]+) shrines$/, '使用 $1 神殿'],
    [/^Day ([\d\.,]+)$/, '天数 $1'],
    [/^level ([\d\.,]+) \/ ([\d\.,]+)$/, '等级 $1 \/ $2'],
    [/^level: ([\d\.,]+) \/ ([\d\.,]+)$/, '等级 $1 \/ $2'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^Login Streak: (.+) days$/, '连续登录：$1 天'],
    [/^Cost: (.+) points$/, '成本：$1 点数'],
    [/^Req: (.+) elves$/, '要求：$1 精灵'],
    [/^Req: (.+) \/ (.+) elves$/, '要求：$1 \/ $2 精灵'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);